/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Dados2;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        index i1= new index();
        i1.setVisible(true);
    }
}
